<?php

/**
 * @file
 * Contains specbee_assignment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function specbee_assignment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the specbee_assignment module.
    case 'help.page.specbee_assignment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a assignment module for Specbee.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function specbee_assignment_theme() {
  return [
    'specbee_assignment' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
